name: Build image

on:
  push:
    branches:
      - 'develop'

jobs:
  build-image:
    name: build Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build & Push Docker image
      run: docker buildx build -t ${{ secrets.DOCKER_USER }}/quarkus-base-image:dev -f ./Dockerfile --push --platform=linux/arm64,linux/amd64 .